version: '3'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        env_file:
          - .env
        image: taivy/ocr_buhuchet
        volumes:
          - C:\\your_volume:/mounted